/** Permission registry — module.action. Roles are configured in DB (role_permissions). */
export const PERMISSIONS: Record<string, string> = {
  'dashboard.view': 'View dashboards',
  'dashboard.consolidated': 'View consolidated multi-branch dashboard',
  'booking.view': 'View bookings', 'booking.create': 'Create bookings', 'booking.edit': 'Edit bookings',
  'booking.cancel': 'Cancel bookings', 'booking.checkin': 'Check-in bookings / issue wristbands',
  'ticket.view': 'View tickets', 'ticket.sell': 'Sell tickets at counter', 'ticket.edit': 'Edit tickets',
  'ticket.override': 'Override ticket rules', 'package.manage': 'Manage packages / ticket types',
  'member.view': 'View members', 'member.create': 'Register members', 'member.edit': 'Edit members',
  'member.delete': 'Close member accounts', 'membership.manage': 'Manage tiers / membership products',
  'points.adjust': 'Adjust member points',
  'credential.view': 'View cards / wristbands', 'credential.issue': 'Issue cards / wristbands',
  'credential.manage': 'Suspend / lost / replace credentials', 'credential.lookup_code': 'Lookup credential by printed code',
  'wallet.view': 'View wallet', 'wallet.topup': 'Wallet top-up', 'wallet.adjust': 'Wallet adjustment',
  'wallet.cashout': 'Refund remaining wallet balance',
  'payment.accept': 'Accept payments', 'payment.verify': 'Verify transfer slips',
  'pos.sell': 'POS sell', 'pos.discount': 'Manual discount', 'pos.void': 'Void orders',
  'kitchen.manage': 'Kitchen display operations',
  'inventory.view': 'View stock', 'inventory.manage': 'Stock in/out/transfer/adjust', 'product.manage': 'Manage products / stores',
  'gate.view': 'View gates', 'gate.scan': 'Submit gate scans', 'gate.approve': 'Approve / deny gate entries',
  'gate.open': 'Manual gate open', 'gate.override': 'Supervisor override (anti-passback etc.)',
  'gate.manage': 'Configure gates', 'gate.emergency': 'Emergency mode',
  'ride.view': 'View rides', 'ride.scan': 'Ride scans', 'ride.operate': 'Operate ride (open/close/pause)',
  'ride.manual_entry': 'Manual ride approve', 'ride.manage': 'Configure rides / scan points',
  'queue.manage': 'Manage virtual queues',
  'locker.use': 'Locker rental at counter', 'locker.manage': 'Configure lockers',
  'promotion.manage': 'Manage promotions / coupons', 'reward.manage': 'Manage rewards',
  'refund.create': 'Create refunds', 'transaction.view': 'View transactions',
  'shift.open': 'Open / close own shift', 'shift.manage': 'View / force close all shifts', 'shift.cash_movement': 'Cash in / out',
  'staff.manage': 'Manage staff', 'role.manage': 'Manage roles & permissions',
  'device.manage': 'Manage devices', 'zone.manage': 'Manage zones', 'branch.manage': 'Manage branches',
  'report.view': 'View reports', 'report.export': 'Export reports',
  'settings.manage': 'System settings', 'audit.view': 'View audit log', 'notification.view': 'View notifications',
  'approval.grant': 'Act as approving manager (Manager PIN)',
};

/** Default device-type permissions when a device authenticates with its API key (no staff logged in). */
export const DEVICE_PERMISSIONS: Record<string, string[]> = {
  GATE_SCANNER: ['gate.scan', 'gate.view'],
  GATE_DISPLAY: ['gate.view'],
  GATE_CONTROLLER: ['gate.view'],
  RIDE_SCANNER: ['ride.scan', 'ride.view'],
  KIOSK: ['ride.view'],
  KITCHEN_DISPLAY: ['kitchen.manage'],
  QUEUE_DISPLAY: [],
  LOCKER_CONTROLLER: [],
  POS: [], PRINTER: [], PAYMENT_TERMINAL: [], CUSTOMER_DISPLAY: [], WRISTBAND_PRINTER: [],
};
